spring:
  profiles:
    active: 
    - dev
---
server:
  port: 7006
  
spring:
  profiles: dev
  application:
    name: microservicecloud-config-eureka-client

eureka:
  #instance:
    #hostname: eureka7001.com
  client:
    register-with-eureka: false
    fetch-registry: false 
    server-url:
      defaultZone: http://eureka-dev.com/eureka/
---
server:
  port: 7007
  
spring:
  profiles: test
  application:
    name: microservicecloud-config-eureka-client

eureka:
  #instance:
    #hostname: eureka7001.com
  client:
    register-with-eureka: false
    fetch-registry: false
    server-url:
      defaultZone: http://eureka-dev.com/eureka/