spring:
  profiles:
    active: 
    - dev
---
server:
  port: 8001
  
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml 
  type-aliases-package: edu.hbmd.taotao.entities   
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                    
    
spring:
   profiles: dev
   application:
    name: microservicecloud-dept 
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource            
    driver-class-name: org.gjt.mm.mysql.Driver             
    url: jdbc:mysql://localhost:3306/clouddb01              
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                                           
      initial-size: 5                                     
      max-total: 5                                         
      max-wait-millis: 200                                  
      
eureka:
  client: 
    service-url: 
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7006/eureka/    
  instance:
    instance-id: microservicecloud-dept8011
    prefer-ip-address: true    

info: 
  app.name: taotao-microservicecloud
  company.name: edu.hbmd.taotao
  build.artifactId: $project.artifactId$
  build.version: $project.version$
---
server:
  port: 8001
  
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml 
  type-aliases-package: edu.hbmd.taotao.entities   
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                    
    
spring:
   profiles: test
   application:
    name: microservicecloud-dept 
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource            
    driver-class-name: org.gjt.mm.mysql.Driver             
    url: jdbc:mysql://localhost:3306/clouddb02              
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                                           
      initial-size: 5                                     
      max-total: 5                                         
      max-wait-millis: 200                                  
      
eureka:
  client: 
    service-url: 
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7006/eureka/    
  instance:
    instance-id: microservicecloud-dept8011
    prefer-ip-address: true    

info: 
  app.name: taotao-microservicecloud
  company.name: edu.hbmd.taotao
  build.artifactId: $project.artifactId$
  build.version: $project.version$